import swaggerJsdoc from "swagger-jsdoc";
import { log } from "../utilies/log";
const options = {
    apis: ["./dist/Features/users/user.router.js"],
    swaggerDefinition: {
        basepath: "/",
        info: {

            description: "Cruze 4 Cash",
            title: "API OF CRUZE FOR CASH",
            version: "0.0.2",
        },
        schemes: {
            name: "http",
        },
        securityDefinitions: {
            Bearer: {
                description: "For accessing the API a valid JWT token must be passed in all the queries in the Authorization header A valid JWT token is generated by the API and retourned as answer of a call to the route /login giving a valid user & password. The following syntax must be used in the Authorization header : \n Bearer: xxxxxx.yyyyyyy.zzzzzz",
                in: "header",
                name: "authorization",
                type: "apiKey",
            }
        },
    },
};
const spec = swaggerJsdoc(options);
export default spec;
